### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data/aicity2022/AIC22_Track1_MTMC_ID10/tracker/ByteTrack/src/fm_tracker/zone/'

### ISSUE THREAD

**Issue by cmtsai** [royukira/AIC22_Track1_MTMC_ID10#2]
Hi!
When running "run_mtmc.sh", it produces as follows errors:
 Traceback (most recent call last):
  File "fair_app.py", line 16, in <module>
    from fm_tracker.byte_tracker import BYTETracker
  File "/data/aicity2022/AIC22_Track1_MTMC_ID10/tracker/ByteTrack/src/fm_tracker/byte_tracker.py", line 14, in <module>
    from .zone import zone
  File "/data/aicity2022/AIC22_Track1_MTMC_ID10/tracker/ByteTrack/src/fm_tracker/zone.py", line 63, in <module>
    for img_name in os.listdir(ZONE_PATH):
FileNotFoundError: [Errno 2] No such file or directory: '/data/aicity2022/AIC22_Track1_MTMC_ID10/tracker/ByteTrack/src/fm_tracker/zone/'

In zone.py file line 61
ZONE_PATH = f"{os.path.dirname(__file__)}/zone/"
ZONE_AREAS = {}
for img_name in os.listdir(ZONE_PATH):
    camnum = int(img_name.split('.')[0][-3:])
    zone_img = cv2.imread(opj(ZONE_PATH, img_name))
    ZONE_AREAS[camnum] = zone_img

What is the images in subdirectory zone/?
Please support these images.

Thank you very much for your works.

**Comment by royukira** [comment]
@cmtsai Sorry for the mistake. I have uploaded the images to `tracker/ByteTrack/src/fm_tracker/zone` and `reid/reid_matching/tools/zone`.  Please try it again.

**Comment by cmtsai** [comment]
Thank you for your works.
