### ISSUE TITLE
Published Paper

### ISSUE THREAD

**Issue by Shk-aftab** [royukira/AIC22_Track1_MTMC_ID10#4]
Can you provide the research paper?

**Comment by royukira** [comment]
> Can you provide the research paper?

Sorry, I'm afraid that I can't help you. We only submitted the [paper](https://openaccess.thecvf.com/content/CVPR2022W/AICity/papers/Xu_Natural_Language-Based_Vehicle_Retrieval_With_Explicit_Cross-Modal_Representation_Learning_CVPRW_2022_paper.pdf) for the track 2 beacause the deadline was pressing.
